server:
  port: 8003

spring:
  r2dbc:
    r2dbc:h2:file:///./data/db_students;DB_CLOSE_DELAY=-1;MODE=PostgreSQL:
    username: sa
    password:
    pool:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  jwt:
    secret: "MUVFQTJCQkFCMzI0MzkyM0E5QjlGNTU2REMyNDlEQTdEMjUyMUNBODFDQkE4"

  api_url_v: /api/v1


